AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Surl - 서버리스 URL 단축 서비스

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Handler: app.handler

Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create/
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /create
            Method: post

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/redirect/
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  CreateFunctionArn:
    Description: Create Lambda ARN
    Value: !GetAtt CreateFunction.Arn
  RedirectFunctionArn:
    Description: Redirect Lambda ARN
    Value: !GetAtt RedirectFunction.Arn
