AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Surl - 서버리스 URL 단축 서비스

Globals:
  Function:
    Runtime: python3.12
    Timeout: 20
    MemorySize: 256

Resources:
  # 카운터 테이블 추가
  SurlCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SurlCounter
      PrimaryKey:
        Name: counter_name
        Type: String
  # DynamoDB 테이블 추가
  SurlMappingTable:
    Type: AWS::Serverless::SimpleTable # 간단한 PK 구조일 때 사용
    Properties:
      PrimaryKey:
        Name: shortCode
        Type: String
  # 클릭 로그 테이블 (트렌드 분석용) - 개별 Row 저장, 400KB 제한 회피
  SurlClickLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
  # 공통 모듈(common/base62) 포함을 위해 CodeUri: src/, Handler만 분리
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create.app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SurlMappingTable
          COUNTER_TABLE_NAME: !Ref SurlCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SurlMappingTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SurlCounterTable
        - Statement:
          - Effect: Allow
            Action: "bedrock:InvokeModel"
            Resource: "arn:aws:bedrock:ap-northeast-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /create
            Method: post

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: redirect.app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SurlMappingTable
          LOG_TABLE_NAME: !Ref SurlClickLogsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SurlMappingTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SurlClickLogsTable
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  CreateFunctionArn:
    Description: Create Lambda ARN
    Value: !GetAtt CreateFunction.Arn
  RedirectFunctionArn:
    Description: Redirect Lambda ARN
    Value: !GetAtt RedirectFunction.Arn
