AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Surl - AI 트렌드 리포트 가시성이 개선된 모니터링 대시보드

Globals:
  Function:
    Runtime: python3.12
    Timeout: 20
    MemorySize: 256

Resources:
  SurlCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SurlCounter
      PrimaryKey: { Name: counter_name, Type: String }

  SurlMappingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: { Name: shortCode, Type: String }

  SurlClickLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create.app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SurlMappingTable
          COUNTER_TABLE_NAME: !Ref SurlCounterTable
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref SurlMappingTable }
        - DynamoDBCrudPolicy: { TableName: !Ref SurlCounterTable }
        - Statement:
            - Effect: Allow
              Action: "bedrock:InvokeModel"
              Resource: "arn:aws:bedrock:ap-northeast-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
      Events:
        CreateApi:
          Type: Api
          Properties: { Path: /create, Method: post }

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: redirect.app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SurlMappingTable
          LOG_TABLE_NAME: !Ref SurlClickLogsTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref SurlMappingTable }
        - DynamoDBCrudPolicy: { TableName: !Ref SurlClickLogsTable }
        - Statement:
            - Effect: Allow
              Action: [ "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents" ]
              Resource: "*"
      Events:
        RedirectApi:
          Type: Api
          Properties: { Path: "/{shortCode}", Method: get }

  TrendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: trend.app.handler
      Environment:
        Variables:
          LOG_TABLE_NAME: !Ref SurlClickLogsTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref SurlClickLogsTable }
        - Statement:
            - Effect: Allow
              Action: "bedrock:InvokeModel"
              Resource: "arn:aws:bedrock:ap-northeast-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
      Events:
        TrendApi:
          Type: Api
          Properties: { Path: /trend, Method: get }

  SurlOperationDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: Surl-Advanced-Operation-Dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric", "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "Traffic Overview",
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${CreateFunction}", { "label": "Create" } ],
                  [ "...", "Invocations", "FunctionName", "${RedirectFunction}", { "label": "Redirect" } ],
                  [ "...", "Invocations", "FunctionName", "${TrendFunction}", { "label": "Trend" } ]
                ],
                "view": "timeSeries", "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric", "x": 12, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "Performance: Latency",
                "metrics": [
                  [ "AWS/Lambda", "Duration", "FunctionName", "${CreateFunction}", { "stat": "p90" } ],
                  [ "...", "Duration", "FunctionName", "${RedirectFunction}", { "stat": "p90" } ],
                  [ "...", "Duration", "FunctionName", "${TrendFunction}", { "stat": "p90" } ]
                ],
                "view": "timeSeries", "region": "${AWS::Region}"
              }
            },
            {
              "type": "log", "x": 0, "y": 6, "width": 24, "height": 8,
              "properties": {
                "title": "AI Trend Analysis Report (AI 트렌드 분석 리포트)",
                "region": "${AWS::Region}",
                "query": "SOURCE '/aws/lambda/${TrendFunction}' | filter @message like /REPORT_DATA:/ | parse @message \"REPORT_DATA: [*] * [*] * [*] *\" as fieldTag, popular, reasonTag, reason, summaryTag, summary | display @timestamp, popular as `인기분야`, reason as `클릭사유`, summary as `한줄요약` | sort @timestamp desc | limit 5",
                "view": "table"
              }
            }
          ]
        }

  CreateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateFunction}"
      RetentionInDays: 7
  RedirectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RedirectFunction}"
      RetentionInDays: 7
  TrendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TrendFunction}"
      RetentionInDays: 7

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'